# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/SaleCalc-back-0.0.1-SNAPSHOT.jar /app/salecalc-back.jar

# Copy the development properties file
COPY src/main/resources/application-dev.properties /app/application.properties

# Expose port 9090
EXPOSE 9090

# Run the application
CMD ["java", "-jar", "salecalc-back.jar"]